language: java
branches:
  only:
    - Feature/ForecastTrigger

notifications:
   email:
     - akmehra@iu.edu
     - pmpande@iu.edu

jdk:
  - oraclejdk8
sudo: required

before_install: 
  - cd "StormCheck" && mvn clean install -Dmaven.test.skip=true -DskipTests=true

install:
  - docker build -t stormcheck .
  - docker run -d -p 127.0.0.1:80:80 --name StormCheck stormcheck

services:
  - docker

before_deploy:
  - cd ..
  - zip -r TeamFlash_ForecastTrigger.zip StormCheck scripts appspec.yml || true
  - mkdir -p "forecastTrigger"
  - mv TeamFlash_ForecastTrigger.zip forecastTrigger/ForecastTrigger.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamflashwest
    local_dir: forecastTrigger
    region: us-west-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: Feature/ForecastTrigger


  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamflashwest
    key: ForecastTrigger.zip
    bundle_type: zip
    application: TeamFlash
    deployment_group: TeamFlash
    region: us-west-1
    on:
      branch: Feature/ForecastTrigger
